version: '3.8'

services:
  etudiants-backend:
    build:
      context: ./etudiants-service/backend
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.etudiants-backend.rule=Host(`localhost`) && PathPrefix(`/etudiants`)"
      - "traefik.http.services.etudiants-backend.loadbalancer.server.port=8082"

  etudiants-frontend:
    build:
      context: ./etudiants-service/frontend
    ports:
      - "9002:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.etudiants-frontend.rule=Host(`localhost`) && PathPrefix(`/etudiants-ui`)"
      - "traefik.http.services.etudiants-frontend.loadbalancer.server.port=80"

  cours-backend:
    build:
      context: ./cours-service/backend
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cours-backend.rule=Host(`localhost`) && PathPrefix(`/cours`)"
      - "traefik.http.services.cours-backend.loadbalancer.server.port=8081"

  cours-frontend:
    build:
      context: ./cours-service/frontend
    ports:
      - "9001:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cours-frontend.rule=Host(`localhost`) && PathPrefix(`/cours-ui`)"
      - "traefik.http.services.cours-frontend.loadbalancer.server.port=80"

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "8090:8080" # Port pour l'interface Traefik (facultatif)
      - "80:80"     # Port utilisé par les services
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
